### ISSUE TITLE
Different vocabs for different data pairs

### ISSUE THREAD

**Issue by Fije** [keithecarlson/StyleTransferBibleData#1]
Hi, great work.

I had a question about the setup: for the Seq2Seq model, in your README's train example, 2 vocab parameters (source and target) are specified - I understand for training public->public, naturally source&target vocabs are the same. Should I then build 2 different vocabs for source & target, when I want to train for example from BBE->YLT?

Many thanks!

**Comment by keithecarlson** [comment]
In our experiments we used the same vocabulary, which was based on a combination of all of our Bible versions, for everything.  If you are trying to closely reproduce our results you probably should do the same.  It is possible to build separate vocabularies for each version and use these more specific versions as you suggest, so you can of course experiment and see how the results change.

**Comment by Fije** [comment]
I see! Will try to experiment with that. Thank you.
